  var audio = ['stimuli/long/a-do.mp3',
		'stimuli/long/a-do8.mp3',
		'stimuli/long/a-fa.mp3' ,
		'stimuli/long/a-fi.mp3' ,
		'stimuli/long/a-la.mp3' ,
		'stimuli/long/a-le.mp3' ,
		'stimuli/long/a-me.mp3' ,
		'stimuli/long/a-mi.mp3' ,
		'stimuli/long/a-ra.mp3' ,
		'stimuli/long/a-re.mp3' ,
		'stimuli/long/a-sol.mp3',
		'stimuli/long/a-te.mp3' ,
	 	'stimuli/long/a-ti.mp3' ,
		'stimuli/long/c-do.mp3' ,
		'stimuli/long/c-do8.mp3',
		'stimuli/long/c-fa.mp3' ,
		'stimuli/long/c-fi.mp3' ,
		'stimuli/long/c-la.mp3' ,
		'stimuli/long/c-le.mp3' ,
		'stimuli/long/c-me.mp3' ,
		'stimuli/long/c-mi.mp3' ,
		'stimuli/long/c-ra.mp3' ,
		'stimuli/long/c-re.mp3' ,
		'stimuli/long/c-sol.mp3',
		'stimuli/long/c-ti.mp3' ,
		'stimuli/long/e-ra.mp3' ,
		'stimuli/long/e-do.mp3' ,
		'stimuli/long/e-do8.mp3',
		'stimuli/long/e-fa.mp3' ,
		'stimuli/long/e-fi.mp3' ,
		'stimuli/long/e-la.mp3' ,
		'stimuli/long/e-le.mp3' ,
		'stimuli/long/e-me.mp3' ,
		'stimuli/long/e-mi.mp3' ,
		'stimuli/long/e-ra.mp3' ,
		'stimuli/long/e-re.mp3' ,
		'stimuli/long/e-sol.mp3',
		'stimuli/long/e-te.mp3' ,
		'stimuli/long/e-ti.mp3' ,
		'stimuli/long/c-do.mp3' , 
		'stimuli/long/c-do.mp3', 
		'new_stimuli/mp3/melody_1_^3_v1_^5_v3_v2_^3_.mp3',
		'new_stimuli/mp3/melody_1_v1+_^2_.mp3',
		'new_stimuli/mp3/melody_6_^1_v5_.mp3',
		'new_stimuli/mp3/melody_^1_v6_v5+_.mp3',
		'new_stimuli/mp3/melody_^2_^4_v3_v2_v1_v3_v2+_^3_^5+_.mp3',
		'new_stimuli/mp3/melody_^3_^4_^5 _^6_v5_v4_v3_v2_v1_.mp3',
		'new_stimuli/mp3/melody_^3_^4_v2_v7_^1_^2_^3_3_^4_.mp3',
		'new_stimuli/mp3/melody_^4_^5_^6_v5_v4_v3_v2_.mp3',
		'new_stimuli/mp3/melody_^4_v6-_v5-_^6-_^4_v2-_2-_.mp3',
		'new_stimuli/mp3/melody_^6_v4_v3_^4_^5_.mp3',
		'new_stimuli/mp3/melody_^6_v5+_v4_^5+_v3_v1_v7-_.mp3',
		'new_stimuli/mp3/melody_v1_^2_v1_v7_^1_^3_v2_.mp3',
		'new_stimuli/mp3/melody_v1_v7-_^7_.mp3',
		'new_stimuli/mp3/melody_v2_2_^3_^4_v2_.mp3',
		'new_stimuli/mp3/melody_v3_v2_v1_.mp3',
		'new_stimuli/mp3/melody_v5-_v3_3_^4+_v3_.mp3',
		'new_stimuli/mp3/melody_v5_^6+_^7_^1_5_.mp3',
		'new_stimuli/mp3/melody_v5_v4_v3_v2_v1_.mp3',
		'new_stimuli/mp3/melody_v5_v4_v6+_^7_^3+_v3_v2_v5_^4_.mp3',
		'new_stimuli/mp3/melody_v7_v6_v5_^6_v5_v4_^5_^6_v5_.mp3', 
		'new_stimuli/mp3/melody_v2_v1_.mp3',
		'new_stimuli/mp3/melody_^1_^2+_.mp3',
		'new_stimuli/mp3/melody_v5_v1+_.mp3',
		'new_stimuli/mp3/melody_^2_v7-_.mp3',
		'new_stimuli/mp3/melody_^5_^1+_.mp3'
			 ];

