  var audio = ['stimuli/long/a-do.mp3',
		'stimuli/long/a-do8.mp3',
		'stimuli/long/a-fa.mp3' ,
		'stimuli/long/a-fi.mp3' ,
		'stimuli/long/a-la.mp3' ,
		'stimuli/long/a-le.mp3' ,
		'stimuli/long/a-me.mp3' ,
		'stimuli/long/a-mi.mp3' ,
		'stimuli/long/a-ra.mp3' ,
		'stimuli/long/a-re.mp3' ,
		'stimuli/long/a-sol.mp3',
		'stimuli/long/a-te.mp3' ,
	 	'stimuli/long/a-ti.mp3' ,
		'stimuli/long/c-do.mp3' ,
		'stimuli/long/c-do8.mp3',
		'stimuli/long/c-fa.mp3' ,
		'stimuli/long/c-fi.mp3' ,
		'stimuli/long/c-la.mp3' ,
		'stimuli/long/c-le.mp3' ,
		'stimuli/long/c-me.mp3' ,
		'stimuli/long/c-mi.mp3' ,
		'stimuli/long/c-ra.mp3' ,
		'stimuli/long/c-re.mp3' ,
		'stimuli/long/c-sol.mp3',
		'stimuli/long/c-ti.mp3' ,
		'stimuli/long/e-ra.mp3' ,
		'stimuli/long/e-do.mp3' ,
		'stimuli/long/e-do8.mp3',
		'stimuli/long/e-fa.mp3' ,
		'stimuli/long/e-fi.mp3' ,
		'stimuli/long/e-la.mp3' ,
		'stimuli/long/e-le.mp3' ,
		'stimuli/long/e-me.mp3' ,
		'stimuli/long/e-mi.mp3' ,
		'stimuli/long/e-ra.mp3' ,
		'stimuli/long/e-re.mp3' ,
		'stimuli/long/e-sol.mp3',
		'stimuli/long/e-te.mp3' ,
		'stimuli/long/e-ti.mp3' ,
		'stimuli/long/c-do.mp3' , 
		'stimuli/long/c-do.mp3' ];

