  var audio = ['stimuli/a-do.mp3',
		'stimuli/a-do8.mp3',
		'stimuli/a-fa.mp3' ,
		'stimuli/a-fi.mp3' ,
		'stimuli/a-la.mp3' ,
		'stimuli/a-le.mp3' ,
		'stimuli/a-me.mp3' ,
		'stimuli/a-mi.mp3' ,
		'stimuli/a-ra.mp3' ,
		'stimuli/a-re.mp3' ,
		'stimuli/a-sol.mp3',
		'stimuli/a-te.mp3' ,
		'stimuli/a-ti.mp3' ,
		'stimuli/c-do.mp3' ,
		'stimuli/c-do8.mp3',
		'stimuli/c-fa.mp3' ,
		'stimuli/c-fi.mp3' ,
		'stimuli/c-la.mp3' ,
		'stimuli/c-le.mp3' ,
		'stimuli/c-me.mp3' ,
		'stimuli/c-mi.mp3' ,
		'stimuli/c-ra.mp3' ,
		'stimuli/c-re.mp3' ,
		'stimuli/c-sol.mp3',
		'stimuli/c-ti.mp3' ,
		'stimuli/e-ra.mp3' ,
		'stimuli/e-do.mp3' ,
		'stimuli/e-do8.mp3',
		'stimuli/e-fa.mp3' ,
		'stimuli/e-fi.mp3' ,
		'stimuli/e-la.mp3' ,
		'stimuli/e-le.mp3' ,
		'stimuli/e-me.mp3' ,
		'stimuli/e-mi.mp3' ,
		'stimuli/e-ra.mp3' ,
		'stimuli/e-re.mp3' ,
		'stimuli/e-sol.mp3',
		'stimuli/e-te.mp3' ,
		'stimuli/e-ti.mp3' ,
		'stimuli/c-do.mp3' ,
		'stimuli/c-do.mp3' ];

